### ISSUE TITLE
从第二页开始的条目序号不正确

### ISSUE THREAD

**Issue by EdiTurn** [dkwingsmt/plugin-wheres-my-fuel-gone#19]
第一页：
![default](https://user-images.githubusercontent.com/5492805/33159263-5098dc16-d04c-11e7-9cde-b06a3b356732.PNG)

第二页：
![2](https://user-images.githubusercontent.com/5492805/33159265-5279227a-d04c-11e7-897a-284053a857f7.PNG)

如果所示，只有第一页的条目序号是正常的。从第二页开始，每页第一条的序号都会多出所设置的每页条目数。

**Comment by dkwingsmt** [comment]
已修复。非常感谢。
