### ISSUE TITLE
插件开关失效

### ISSUE THREAD

**Issue by JenningsWu** [dkwingsmt/plugin-wheres-my-fuel-gone#2]
in index.cjsx

```
if config.get('plugin.WheresMyFuelGone.enable', true)
  initialPluginWindow()

module.exports =
  name: 'Where\'s My Fuel Gone'
```

没记错的话本体在管理插件开或关时，所用到的字段`plugin.pluginName.enable`中的`pluginName`是 `module` exports 出来的`name`

**Comment by dkwingsmt** [comment]
这个 name 看起来只是个标识符而已？我直接把它改掉，除了这个 enable 之外，应该没有影响吧？

**Comment by JenningsWu** [comment]
应该没什么影响？

**Comment by dkwingsmt** [comment]
Fixed https://github.com/dkwingsmt/plugin-wheres-my-fuel-gone/commit/e2f3c31438561cc26f7c5205c0486d5d4854ed4f
