### ISSUE TITLE
[Feature Request] 加入对于整个（活动）海域的筛选

### ISSUE THREAD

**Issue by JenningsWu** [dkwingsmt/plugin-wheres-my-fuel-gone#3]
希望能提供一种筛选方式（例如允许海域编号的局部匹配筛选），实现统计整个活动耗费资源数的目的。

**Comment by dkwingsmt** [comment]
那就把海域编号匹配也改成正则好了

**Comment by dkwingsmt** [comment]
solved by https://github.com/dkwingsmt/plugin-wheres-my-fuel-gone/commit/14f82f49893a377d72aeb0301c685576c1c943bc
