### ISSUE TITLE
筛选条件中海域血条筛选有误

### ISSUE THREAD

**Issue by JenningsWu** [dkwingsmt/plugin-wheres-my-fuel-gone#4]
当应用筛选条件“海域尚未斩杀”、“海域已斩杀”时，显示的筛选条件均为”海域尚未斩杀“，并且海域已斩杀的筛选存在错误。

**Comment by dkwingsmt** [comment]
Fixed https://github.com/dkwingsmt/plugin-wheres-my-fuel-gone/commit/d77abefbe0daecce2b6c503e7824958747988961
